- .travis.yml
- README.md
- deployment/README.md
- deployment/terraform/outputs.tf
- docker-compose.ci.yml
- docker-compose.yml
- scripts/cipublish
- scripts/server
- scripts/test
- taui/.gitignore
- taui/Dockerfile
- taui/configurations/staging/settings.yml
This PR sets up a simple dev environment and CI pipeline for the app.
Closes #3 and closes #4.
View a simple deployment of the app at https://echolocator.azavea.com:
* Follow the instructions in [the README](https://github.com/azavea/echo-locator/blob/feature/jfc/mastarm-deployment/README.md#development) for `Developing` and `Testing`, and confirm that they are accurate
* View the Travis output for the reverted commit that allowed a deployment to run from this branch, and confirm that Mastarm deployed properly: https://travis-ci.com/azavea/echo-locator/builds/98670744#L486
> Create dev environment and set up CI to deploy the app

- README.md
- taui/src/test-sass.scss
> Fix serve docs and test SCSS

- taui/configurations/default/messages.yml
- taui/src/components/select-account.js
- taui/src/utils/validate-voucher-number.js
Show error message if entered voucher number does not match expected pattern.
Not accepted:
Accepted:
* Go to http://localhost:9966/search
* 8-digit or 2-character + 6-digit entries should be allowed to select/create profile
* Non-matching voucher number entries should show expected error message
Closes #61.
> Validate voucher number

- taui/configurations/default/messages.yml
- taui/src/components/dock.js
- taui/src/constants.js
Add pagination to the neighborhood list, instead of only showing a few top results.
I opened this PR against #27.
* Next/previous buttons should function as expected
* Buttons should be hidden if next/back not available
* There should be three results per page
Closes #26.
> Paginate neighborhood list

- README.md
- taui/configurations/default/store.yml
Switch to new static results buckets. Also change default to late afternoon, by configuration file ordering.
Closes #91.
> Feature/kak/update network#91

- taui/src/components/map.js
- taui/src/constants.js
> Customize polygon layer styling

- taui/src/components/neighborhood-details.js
- taui/src/utils/google-directions-link.js
Implement Google Directions deep link.
These details...
...link to these directions:
* Directions links should match expected origin, destination, and mode
Closes #107
> Implement Google Directions link

- taui/src/constants.js
Remove fill and slightly increase opacity and weight of boundary.
* Map neighborhood GeoJSON layer should have no fill
Closes #124
> Modify neighborhood bounds map style

- deployment/amplify/production/aws-exports.js
Should have been included with #93.
Merging to fix production login.
> Fix outdated production aws-exports

- taui/configurations/default/messages.yml
- taui/src/components/edit-profile.js
- taui/src/constants.js
- taui/src/sass/06_components/_account-profile.scss
- taui/src/types.js
Add user controls to profile page for setting weighting importance.
Weighting changes to be implemented separately in #123.
* Edit an existing profile
* Should have no errors, and options for new fields should use defaults
* Change one or more importance fields and save profile
* Changes should be reflected on returning to profile page
Closes #122
> Feature/kak/user weight controls#122

- taui/src/components/neighborhood-details.js
Accidentally hidden by #116.
Fixes #137.
> Fix missing route summaries

- taui/src/selectors/neighborhoods-sorted-with-routes.js
Rank neighborhoods by accessibility (travel time), violent crime, and schools, using weights based on the user profile importance settings. Factors set to 'not important' are ignored, unless all three are set as 'not important', in which case all are ranked equally.
* Ranking all factors the same should produce the same result, regardless of which importance
* Ranking one factor as => 'important' and the other two as not should ignore the unimportant
* Set profile to 'will have car' with only accessibility as important should rank by distance
Closes #123
> Weight by user-set importance

- taui/src/components/neighborhood-details.js
> Fix mode in directions link

- taui/package.json
- taui/yarn.lock
> Update mastarm to fix Safari polyfills

- taui/package.json
- taui/src/components/draw-route.js
- taui/src/components/map.js
- taui/yarn.lock
Fix user zooming in detail view.
* Map should still zoom to fit route on going to details
* Using the zoom control should behave as expected, particularly in detail view
* Map should still zoom to fit all neighborhoods on returning to list
Fixes #216.
> Bugfix/kak/fix detail user zoom#216

- taui/configurations/default/messages.yml
- taui/src/components/dock.js
- taui/src/components/form.js
- taui/src/components/main-page.js
- taui/src/components/meter.js
- taui/src/components/neighborhood-list-info.js
- taui/src/components/rental-units-meter.js
- taui/src/constants.js
- taui/src/sass/01_settings/_color.scss
- taui/src/sass/06_components/_map-sidebar.scss
- taui/src/sass/06_components/_neighborhood-facts.scss
- Distinct green/yellow/orange chart colors
- "Show transit times…" form header
- "Your recommended neighborhoods 1–3 of 56"
- Tooltip styles
- "School choice" style
- Copy changes per client
> Misc polish

- taui/yarn.lock
Minor package updates.
Fixes #228.
> Update packages, including mastarm

- taui/src/components/neighborhood-details.js
- taui/src/sass/06_components/_neighborhood-details.scss
- taui/src/utils/google-maps-link.js
- taui/yarn.lock
Pick up mastarm update and its minor package updates.
> Minor package updates

- taui/configurations/default/messages.yml
- taui/src/components/edit-profile.js
- taui/src/sass/06_components/_account-profile.scss
- taui/src/sass/06_components/_convert-to-account.scss
- taui/src/sass/07_layouts/_form-screen.scss
- taui/src/sass/main.scss
Style the client account creation form added in #275 
Refactored the DOM to move the form into its own section. Changed classnames. Added and edited some messages.
> Style client account creation form

- taui/configurations/default/messages.yml
- taui/src/components/neighborhood-list-info.js
- taui/src/sass/06_components/_neighborhood-facts.scss
- taui/src/sass/06_components/_rental-units-meter.scss
Copy and style tweaks to the ECC profile checkbox and sidebar fact introduced in #281.
Introduces a tooltip for the ECC sidebar fact, which needs content.
> Style ECC UI

- taui/package.json
- taui/yarn.lock
Minor dependency updates only; merging.
> Minor dependency updates

- deployment/amplify/production/amplify/backend/auth/echolocatorProdAuth/parameters.json
Update Cognito email template to remove period after temporary password.
Closes #315.
> Remove period after password in email template

- taui/src/selectors/neighborhoods-sorted-with-routes.js
- taui/yarn.lock
Fixes a neighborhood weighting/sorting issue when crime is marked "very important."
Also makes some minor package updates.
Before:
After:
* Add profile address 1050 Adams Street, Dorchester Center (or use profile `22222222`)
* Sorting should behave differently than on staging
Fixes #321
> Fix overweighting crime
