azavea/echo-locator

.gitignore
deployment/README.md
deployment/terraform/cdn.tf
deployment/terraform/certificate.tf
deployment/terraform/config.tf
deployment/terraform/dns.tf
deployment/terraform/storage.tf
deployment/terraform/variables.tf
docker-compose.ci.yml
scripts/infra

Perform initial Terraform setup, including a CloudFront CDN and S3 origin for the app. In addition, set up the foundation for the staging site at https://echolocator.azavea.com.
Closes #2.
Visit https://echolocator.azavea.com to see a hello world message:
* Create an `echo-locator` AWS profile using access credentials for the Professional Services account:
```
aws configure --profile echo-locator
```
* Run Terraform plan: 
```
docker-compose -f docker-compose.ci.yml run --rm terraform ./scripts/infra plan
```
* Confirm that the plan comes out clean
* Visit https://echolocator.azavea and confirm:
* Page loads properly
* Certificate valid
* Content is the same as http://echo-locator-staging-site-us-east-1.s3.amazonaws.com/index.html

Initialize Terraform with CloudFront CDN and S3 origin

---

docker-compose.yml

Instead of only mounting `taui/src/` into the Taui container, mount the entire `taui` directory. This allows assets and other directories to be passed between the host and the guest.
* I believe this change was preventing updates from getting deployed to the staging site.
* Run `./scripts/server` to rebuild
* Confirm that everything looks good

Mount entire Taui directory into Docker guest

---

scripts/build
taui/.eslintrc.json
taui/package.json
taui/src/actions/geocode.js
taui/src/components/map.js

- pass through live reload flag to server (`mastarm` uses [budo](https://github.com/mattdesl/budo))
- add explicit linter configuration (copy `mastarm` linter settings)
- linting
- add a separate build script (currently only have a `server` script that also builds)
- `./scripts/build` should build container but not start server
- `./scripts/server`
- visit site
- edit a source file
- ~server should live reload site~
- change should be visible on site
Closes #11.

Feature/kak/live reload#11

---

taui/configurations/default/messages.yml
taui/src/amplify-theme.js
taui/src/components/application.js
taui/src/components/custom-header-bar.js
taui/src/components/custom-sign-in.js
taui/src/components/with-authenticator.js
taui/src/index.css
taui/src/index.js

Customizes sign-in page and adds a customized navbar with a logout button.
This will need some styling cleanup (i.e., the existing taui blue probably isn't the BHA blue we want), but sets up the customized sign-in and header bar components alongside a custom Amplify theme that readies the app for further styling work and header bar customization.
The logged-in user name is currently displayed in the header bar; as part of implementing account selection/switching, that should be changed to match the current account, as in the wireframes.
The Amplify theme styling is currently defined near the top of `index.js`, defined as `CustomAuthenticatorTheme`. Ideally, these rules would go in a CSS file instead. I'm not sure how best to handle that.
- `./scripts/serve`
- Clear local storage for …

Feature/kak/amplify theme#35

---

deployment/README.md
taui/configurations/production/settings.yml
taui/configurations/staging/settings.yml

Make a few small changes to support a new production deployment, including:
* Update deployment README to reflect lessons learned from standing up production resources
* Add new production settings file for Taui
Closes #5.
* We still don't have a production domain. I pushed up resources using the domain https://echolocator-prd.azavea.com, but we'll have to either A) consider this PR blocked or B) go with the temporary domain while we wait for the real domain.
* Run a production deployment locally:
```console
$ export AWS_ACCESS_KEY=<echo-locator-access-key>
$ export AWS_SECRET_ACCESS_KEY=<echo-locator-secret-access-key>
$ export ENV=production
$ ./scripts/cipublish
```
* Navigate to https://echolocator-prd.azavea.com and confirm that it looks good

Configure production resources

---

taui/configurations/default/messages.yml
taui/src/components/application.js
taui/src/components/custom-header-bar.js
taui/src/components/edit-profile.js
taui/src/components/geocoder.js
taui/src/components/main-page.js
taui/src/components/select-account.js
taui/src/components/with-authenticator.js
taui/src/constants.js
taui/src/sass/06_components/_account-profile.scss
taui/src/sass/06_components/_app-header.scss
taui/src/sass/main.scss
taui/src/types.js

Add page with a form to enter or edit user profile. Modify search to only use voucher number and match exactly. (See discussion on #55).
Also adds header links to the search and profile pages, and clears profile on logout.
New profile page:
Search page:
On voucher not found:
The voucher holder name is now an editable field on the profile page, as it is no longer a search/create key.
* Should be able to edit profile at `/profile`
* Should be able to add up to three addresses
* Address geocoder should work as expected
* Changes should be saved to `localStorage` and to S3 on clicking 'go'
* Navigating back to profile page after editing should reflect saved changes
* Clicking 'cancel' should discard changes and navigate to the previous page (search or map)
* 'Edit' header button should …

Feature/kak/profile page#22

---

taui/.sass-lint.yml
taui/.stylelintrc
taui/package.json
taui/yarn.lock

Add some stylelint rules and modify yarn commands for linting.
Add azavea stylelint dependencies.
Companion PR to azavea/mastarm#13.
There are still a number of style lint warnings from `stylelint`. This adds rules to ignore the most noisy of them.
It was necessary to install `stylelint` in this project, although it is also in `mastarm`.
* Copy the `mastarm` version from azavea/mastarm#13 to `taui/node_modules/mastarm`
* `cd taui && yarn lint`
* Should get `stylelint` linter warnings, and no `eslint` warnings

Switch to stylelint

---

taui/configurations/default/messages.yml
taui/src/components/application.js
taui/src/components/custom-header-bar.js
taui/src/components/custom-sign-in.js
taui/src/components/edit-profile.js
taui/src/components/with-authenticator.js
taui/src/config.js
taui/src/constants.js

Allow bypassing login to browse anonymously instead. Store profile in `localStorage` without using S3 for anonymous user. (Profile settings will survive a page refresh but cannot be stored to a remote account when browsing the site anonymously.)
Hide voucher number and voucher holder name, and change "sign out" button to "sign in" in the header when browsing anonymously.
New anonymous sign-in page option:
Anonymous user's profile page and header:
For our use, it is not necessary to enable [unauthenticated roles](https://docs.aws.amazon.com/cognito/latest/developerguide/identity-pools.html) for the Cognito identity pool, as the anonymous user does not need any access to AWS resources. If the anonymous user did need access to S3 or other AWS resources but with different permissions than …

Allow using the site anonymously

---

taui/configurations/default/messages.yml
taui/src/components/form.js
taui/src/components/main-page.js
taui/yarn.lock

Replaces map page form origin/destination geocoder inputs with select inputs on for profile destinations and networks (times of day). Defaults to the profile primary destination and the first listed network ('Late Night', for our currently configured [r5](https://github.com/conveyal/r5) output.)
The other sidebar content apart from these inputs will be replaced in #25, and the map page behavior for loading data will change considerably, so other aspects of the map page behavior broken by this can generally be ignored, as it will be removed in #25 (i.e., start location marker doesn't show on full page reload now.)
I haven't added a control for modes yet as in the wireframe, as we haven't determined if that is something the static router results will practically support as a search …

Feature/kak/map view sidebar#24

---

taui/configurations/default/messages.yml
taui/src/components/select-account.js

Instead of searching directory contents, attempt to get file directly. Check error result to see if it was not found.
* Account search and selection should still work as expected
* Attempting to search for a non-extant account should still prompt to create account
Closes #66.

Get user profile directly from S3

---

taui/configurations/default/messages.yml
taui/src/components/application.js

Handle unmatched routes in the React router. Display a message if the user navigates to a non-extant page.
This returns a `200` and not a `404`, as the routing is handled by the front-end in the "single-page" app.
* Navigating to a page that does not exist should display expected no-match message
* Other routes should continue to function as expected
Closes #60.

Add page-not-found message

---

taui/configurations/default/messages.yml
taui/src/components/dock.js
taui/src/components/main-page.js
taui/src/components/neighborhood-details.js
taui/src/components/neighborhood-list-info.js
taui/src/components/route-card.js
taui/src/components/route-segments.js
taui/src/selectors/neighborhoods-sorted-with-routes.js

Estimate travel times using straight-line distance. Do not show user estimated travel times or transit routes in driving mode.
The static result files from `r5` do not contain non-transit travel times or routes, so instead, estimate times using distance as a proxy and hide routes in driving mode.
Driving mode list:
Details in driving mode (no travel time or route info displayed):
Based on #28; I'll rebase before merge.
These results seem to be somewhat more sensitive to rent differences than transit mode is. I checked that distance ordering was working properly by setting the weights to only use time, and results were ordered as expected strictly by distance from origin.
* Site should continue to work as before with 'will have a car' unchecked on the user profile
* Check 'will have a car' …

Implement driving mode

---

taui/src/sass/07_layouts/_map-screen.scss

Prevents map and sidebar from overflowing browser viewport on Linux browsers.

Prevent viewport overflow on Linux browsers

---

taui/src/components/dock.js

Guard against missing `favorites` property.
Closes #99.

Handle missing favorites

---

taui/src/components/custom-header-bar.js

Fix log in message being shown immediately after login, before user profile has been set.
* Log out, if logged in
* Log in
* Should be directed to profile search page, with header message to 'sign out'
* Clicking to continue anonymously instead of logging in should show message to 'sign in'
Fixes #105

Fix header message after login

---

taui/src/selectors/detail-neighborhood.js

Always look up detail view neighborhood from full list of routable neighborhoods.
* Go to 'saved' sidebar sub-list on map page
* Click the marker for a routable neighborhood that is not saved
* Should get details for neighborhood in sidebar
Fixes #111

Fix finding details neighborhood

---

taui/src/components/dock.js
taui/src/components/neighborhood-details.js
taui/src/components/route-card.js

Fix reversion from styling that added display of drive times. These estimated values should not be displayed to the user anywhere.
Show mode and origin in drive mode list card, but not (estimated) travel time:
Time/mode/origin line hidden entirely in drive mode on detail view:
Transit mode detail, for reference:
* List and detail views in driving mode should not display drive times
* List and detail views in transit mode should still display times and route summaries
Fixes #113

Hide drive times

---

README.md
neighborhood_data/update_data.sh
scripts/cipublish
scripts/imagepublish
taui/configurations/default/settings.yml
taui/configurations/production/settings.yml
taui/configurations/staging/settings.yml
taui/src/components/custom-sign-in.js
taui/src/components/edit-profile.js
taui/src/components/neighborhood-details.js
taui/src/components/route-card.js
taui/src/constants.js
taui/src/types.js
taui/src/utils/neighborhood-images.js

Use and deploy neighborhood image thumbnails downloaded with the image metadata with the `neighborhood_data` data processing scripts, instead of hotlinking to the images. Fixes deploying app images (only affects the logo). Refactor image and image metadata referencing. Also adds `data-private` attribute to text inputs to hide user profile information from LogRocket.
Using locally hosted image:
Since the neighborhood thumbnail images are not under version control and so are not available to the CI environment, deploying those images must be done as a separate step when they are updated. As that data source should only change infrequently, it shouldn't be necessary to do so often. Redeploying via CI should not affect previously deployed neighborhood images.
* `./scripts/imagepublish …

Feature/kak/push images#112

---

taui/src/actions/network.js

On page load, only set origin from app state; do not use configuration default or network center as default.
Fixes #121.

Always get origin from state

---

README.md
taui/.eslintrc.json
taui/configurations/default/messages.yml
taui/src/components/neighborhood-details.js

Show ECC text in neighborhood details for expanded choice zip codes.
* Text should show for ECC neighborhoods (generally, those with images)
* Text should not show for non-ECC neighborhoods
Closes #128

Feature/kak/indicate ecc#128

---

taui/configurations/default/messages.yml
taui/src/components/custom-sign-in.js
taui/src/components/neighborhood-details.js
taui/src/components/neighborhood-list-info.js
taui/src/components/route-card.js
taui/src/types.js
taui/src/utils/neighborhood-properties.js

Remove some detail fields from display that will no longer be used. Add "approximately/about" text before travel times, to indicate they are estimated.
"About" in the list card, as there isn't enough space for "approximately":
"Approximately" before travel time in details:
Fewer detail fields:
Removed greeting text:
* List card and detail card text should look as expected
Closes #138 
Connects #144 
Closes #103

Feature/kak/remove fields#138

---

taui/configurations/default/messages.yml
taui/src/components/edit-profile.js
taui/src/components/neighborhood-details.js
taui/src/components/neighborhood-list-info.js
taui/src/components/route-card.js
taui/src/sass/06_components/_account-profile.scss
taui/src/sass/06_components/_neighborhood-details.scss
taui/src/sass/06_components/_neighborhood-summary.scss

- Style search weight fields on Profile page. Moved car checkbox higher up so it doesn't get lost.
- Render ECC boolean field as another table row in neighborhood summary and detail
- [EDIT:] Unlink thumbnails in search result cards
I first experimented with rendering the ECC field as a sort of tag/badge, but it was too prominent, and looked too similar to the treatment of transit lines on the neighborhood detail page.

Style search weights and ECC field

---

taui/configurations/default/messages.yml
taui/src/components/neighborhood-details.js
taui/src/utils/craigslist-search-link.js

Link out to Craigslist housing search from neighborhood detail page, using neighborhood zip code and the number of bedrooms from the user profile as search parameters. 
Craigslist's map of results from the search is in the same area:
* Go to details for a neighborhood
* Link to search Craigslist should open search in a new tab
* Results should match neighborhood zip code and user profile room count
Closes #131.

Link to Craigslist housing search

---

taui/configurations/default/messages.yml
taui/src/components/form.js
taui/src/components/neighborhood-details.js
taui/src/sass/06_components/_map-sidebar.scss
taui/src/sass/06_components/_neighborhood-details.scss
taui/src/taui.css

- Style ECC checkbox
- Rename ECC checkbox to "Expanded Choice Communities only" and enable by default.
- Adjust copy and order of detail page external links.
- Tweak transit chip size.

ECC checkbox semantics, style. External links.

---

taui/src/components/draw-neighborhood-bounds.js
taui/src/constants.js

Use polygon fills instead of strokes.
Note this PR doesn't alter or add the polygon semantics (eg, see #161). It merely makes `fill` the distinguishing visual characteristic instead of `stroke`.

Polygon fills instead of strokes

---

taui/config.json
taui/configurations/default/messages.yml
taui/configurations/default/store.yml
taui/src/actions/network.js
taui/src/components/edit-profile.js
taui/src/components/form.js
taui/src/components/main-page.js
taui/src/components/route-card.js
taui/src/components/select-account.js
taui/src/selectors/active-network-index.js
taui/src/selectors/draw-isochrones.js
taui/src/selectors/isochrones.js
taui/src/types.js

Add checkbox to user profile to set whether to include commuter rail and express bus in the transit results. Add configuration for two more results buckets that exclude commuter rail and express bus. Based on user profile setting, filter out networks (results buckets) that do not match the new setting, or hide the network selector if in car mode (not using transit results). Also changes the labels for the networks.
With commuter rail/express bus option set, this result for Whitman shows as accessible via the Kingston commuter rail line:
With the commuter rail/express bus option unset, Whitman is greyed out as unaccessible and the drop-down label changes:
Network drop-down hidden in car mode:
The two new buckets appear to not have CORS headers set to allow access from `localhost` in the …

Feature/kak/toggle commuter rail#140

---

taui/src/components/map.js
taui/src/selectors/draw-neighborhood-route.js

Do not draw the final walk leg of transit routes, which goes from the nearest transit stop to the neighborhood centroid. Also do not show marker on neighborhood centroid when displaying route.
Start walk displays from user address to boarding stop. End walk from disembarking stop to neighborhood centroid used for routing is not displayed.
The walk legs were not calculated by the routing engine to follow the street network, but are instead a straight line from the first/last stop to the origin/destination.
* Open a profile in transit mode
* Go to neighborhood details
* Should not have walk leg to neighborhood centroid
Closes #186

Feature/kak/hide walk leg#186

---

taui/src/components/custom-sign-in.js
taui/src/components/with-authenticator.js
taui/src/selectors/neighborhoods-sorted-with-routes.js

Log in on keypress in either username or password sign-in field.
Also fixes a couple of null reference errors that might occur on logout.
The AWS Amplify [React components](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Amplify-UI/Amplify-UI-Components-React.jsx) for the form do not create an HTML form, and so do not [implicitly submit](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission).
* Hit enter in either username or password sign-in field
* Site should attempt to sign in and redirect to profile search if successful
Closes #185

Feature/kak/submit login on enter#185

---

taui/src/components/select-account.js

Skip profile edit page after search if profile already exists and has destinations.
Checks for destinations on profile to guard against pulling up a profile that exists but is incomplete, which would result in staying on the search page, as the `/map` route guards against routing to it without a profile with destinations.
* Log out/back in
* Search for a profile that exists
* Should go direct to map page
* Edit profile button on map page should still function as expected
* Log out/back in
* Search for a profile that does *not* exist
* Should still get prompt to create profile
* Click to complete the profile, but do not complete it (do not add any destinations)
* Log out/back in
* Search for the created, incomplete profile
* Should be directed to profile page
Closes #184.

Go directly to map after setting profile

---

taui/configurations/default/messages.yml
taui/src/components/neighborhood-details.js
taui/src/utils/zillow-search-link.js

Adds a dynamic search link to Zillow rentals in the neighborhood details card.
Details links now are on two lines:
Search opens in new tab:
The links line was getting a little crowded, so I moved the search links to a second line in the details card.
* Go to details for a neighborhood
* Click 'Zillow' button
* Search should open in new tab for neighborhood's zip code and user profile's rooms number
Closes #132

Feature/kak/link zillow#132

---

taui/src/components/neighborhood-details.js
taui/src/utils/craigslist-search-link.js
taui/src/utils/zillow-search-link.js

Add parameters for max price to Craigslist and Zillow searches.
Searches are for zip code 02467 (Chestnut Hill).
Studio Craigslist:
Studio Zillow:
6 bedroom Cragslist:
6 bedroom Zillow:
* Craigslist and Zillow links from neighborhood details should search with max price
* Max price should vary by neighborhood and number of bedrooms on user profile
Closes #171.

Pass maximum subsidy to housing search

---

taui/src/components/neighborhood-details.js
taui/src/components/route-card.js
taui/src/constants.js

Round travel times to nearest five minutes, and show estimated drive times.
82 minutes transit time, rounded to 80:
also in details:
rounded drive times display:
The 'About' term indicating the travel time is an estimate is the same for transit and driving. There's nothing to indicate to the user that the drive time estimates are far less accurate.
* Travel times should be rounded to nearest five minutes
* Travel times should display in drive mode
* Travel times should display as expected in both summary cards and details
Closes #181.
Closes #144.

Round trip times and show drive times

---

taui/src/components/form.js

Display destination purpose type before the address in the map page destination drop-down.
* Map page should load with [destination type]: [address] in the destination drop-down text field
* Drop-down options should match above format
* Toggling destination should still behave as expected
Closes #183.

Display destination type label in drop-down

---

taui/configurations/default/messages.yml
taui/src/components/edit-profile.js
taui/src/components/form.js
taui/src/components/meter.js
taui/src/components/neighborhood-details.js
taui/src/components/neighborhood-list-info.js
taui/src/components/rental-units-meter.js
taui/src/components/route-card.js
taui/src/constants.js
taui/src/sass/01_settings/_color.scss
taui/src/sass/06_components/_account-profile.scss
taui/src/sass/06_components/_map-sidebar.scss
taui/src/sass/06_components/_meter.scss
taui/src/sass/06_components/_neighborhood-details.scss
taui/src/sass/06_components/_neighborhood-facts.scss
taui/src/sass/06_components/_neighborhood-summary.scss
taui/src/sass/06_components/_rental-units-meter.scss
taui/src/sass/main.scss
taui/src/utils/google-maps-link.js

- Replace quintile labels with bar charts and "housing" chart
- Redesign neighborhood detail page
- Add labels to sidebar form fields
- Rename "Violent crime" to "Public safety"
- Drive-by: Profile copy tweaks
- Drive-by: Keep sidebar attribution on bottom
Fixed bug where destination purpose wasn't rendering in detail and search views.
A number of new features are using placeholder values and need to be wired up:
- Schools meter (`neighborhood-list-info.js`)
- Public safety meter (`neighborhood-list-info.js`)
- Rental units meter (`neighborhood-list-info.js`)
- ~Max rent (_twice_ in `neighborhood-details.js`)~
- ~Number of rooms (_twice_ in `neighborhood-details.js`)~
Some of the links in the detail view need to be wired up or adjusted:
- Section 8 link needs a util function
- Zillow link …

UI enhancements

---

taui/Dockerfile
taui/README.md
taui/src/components/meter.js
taui/src/components/neighborhood-list-info.js
taui/src/components/rental-units-meter.js
taui/src/selectors/neighborhoods-sorted-with-routes.js
taui/src/utils/scaling.js
taui/yarn.lock

Implement the meters for school ranking, crime rate, and housing availability from #199. Hide the school ranking meter for school choice zip codes (#179).
The data source provides the education percentile, but only the crime rank quintile. The number of houses to display in the five-house icon chart is provided directly by the data source.
* Meters should display as expected
* Meter shading (orange-yellow, yellow, or green) should match value range
* Housing availability shading and count should display as expected
* School choice zip codes (i.e., Boston-labelled zip codes) should hide school rank meter
Closes #179.

Feature/kak/hide school ranks#179

---

taui/src/sass/06_components/_neighborhood-facts.scss
taui/src/sass/06_components/_neighborhood-summary.scss

Was able to recreate #204 in FF/Win and Edge.
Fixed by decreasing font size and tightening up padding. Tested across browsers.
Resolves #204

Fix chart overflow in FF, Edge

---

taui/package.json
taui/src/components/meter.js
taui/src/components/neighborhood-list-info.js
taui/src/components/rental-units-meter.js
taui/yarn.lock

Adds the [react-tooltip](https://github.com/wwayne/react-tooltip) library and uses it to display tooltips on hover over each of the three neighborhood charts.
This should make it easier for us to add specific tooltips later (we don't have text yet for what to display, or for which elements).
* `cd taui && yarn install && yarn start`
* Go to map page
* Neighborhood chars in both list view and details should have hover interactivity now
Closes #134

Feature/kak/add tooltip library#134

---

neighborhood_data/requirements.txt
neighborhood_data/update_data.sh
taui/src/utils/neighborhood-images.js

Fix neighborhood images with `.png` extensions not appearing properly in the UI by reading the extension from the source URL used to download the cached thumbnail, instead of expecting all to be `.jpg` files.
Also adds calling a small Python image compression library to the data processing script pipeline, to make a pass at lossless compression of the cached thumbnail images for web presentation, to speed site responsiveness a bit.
Before (on staging):
After:
Some output from the image compression library (most didn't need any optimization):
* `cd taui && yarn start`
* View neighborhood card for `Harvard  - 01451` 
* Picture on list view should show as expected
* Both pictures should show as expected in detail page
Fixes #209

Fix png image references

---

taui/configurations/default/messages.yml
taui/src/components/application.js
taui/src/components/dock.js
taui/src/components/draw-neighborhood-bounds.js
taui/src/components/draw-route.js
taui/src/components/main-page.js
taui/src/components/map.js
taui/src/components/route-card.js
taui/src/constants.js
taui/src/index.js
taui/src/selectors/active-neighborhood-bounds.js
taui/src/selectors/index.js
taui/src/selectors/neighborhoods-sorted-with-routes.js
taui/src/selectors/network-neighborhood-routes.js
taui/src/selectors/routable-neighborhoods.js
taui/yarn.lock

Modify map interactivity:
- make tooltips dynamic (show message in toolitp if neighborhood is not reachable)
- make map marker green on list card hover (fixes #212)
- set active neighborhood on map hover in list view, but not detail view (shows route)
- style reachable neighborhood bounds as green on hover in both list and detail views
On list card or neighborhood map bounds hover:
Hovering over a reachable neighborhood in details view:
Hovering over a non-reachable neighborhood in details view (see tooltip at bottom):
The end leg and neighborhood centroid end marker were removed from route rendering in #189, as requested by the client. The centroid markers are still present here in list view for the three currently listed neighborhoods, but not in the detail view, and the end leg does …

Feature/kak/hover interactivity#161

---

taui/src/selectors/neighborhoods-sorted-with-routes.js

Modify neighborhood weighting algorithm to:
- always give travel time (accessibility) extra weight over the other two variables
- weight schools differently when schools are given maximum importance
- treat the safest two quintiles for violent crime equally
All profile options weighted equally, top transit results:
Default profile options weights (travel time 'important', other two 'somewhat'):
Schools 'very important', other two options 'not important':
Travel time effectively always has a one higher importance rating than whatever it has assigned in the profile with this.
When schools are ranked as 'very important' (and the other two options aren't also 'very important'), this changes the algorithm to weight by percentile binned into quarters; for other school importance rankings, or …

Feature/kak/modify weighting#178

---

taui/configurations/default/messages.yml
taui/src/components/dock.js
taui/src/components/neighborhood-list-info.js
taui/src/components/rental-units-meter.js
taui/src/constants.js

Generate dynamic rental units tooltips. Support links in tooltip text.
To support having clickable links in the tooltips, they do not dismiss until the user clicks somewhere. For this tooltip, the provided text did not include a link. I've added one to the MAPC site (sited as the data source).
* Tooltip should appear on hovering over rental unit houses chart in list and detail views
* Tooltip should dismiss on clicking somewhere
* Clicking the "MAPC" text in the tooltip should open the MAPC site in a new tab
* Tooltip text above/about/below average text should correspond number of houses
* Total number of MAPC units in the zip code should appear, comma-separated, in the tooltip
Closes #221

Feature/kak/rental units tooltip#221

---

taui/src/components/dock.js

When paging search results, or when switching between search and detail views, the sidebar is now automatically scrolled to the top.
* Make browser viewport short enough to require sidebar scrolling.
* Page search results forward and backward, with sidebar scrolled each time…
* … new pages should always start with sidebar scrolled to top
* Same when drilling into detail view, and returning back to search

Scroll sidebar to top when paging or switching search/detail view

---

taui/configurations/default/messages.yml
taui/src/components/meter.js
taui/src/components/neighborhood-list-info.js
taui/src/components/rental-units-meter.js
taui/src/constants.js

Add dynamic text with hyperlinks to the tooltips for the "public safety" neighborhood charts.
Tooltip for a Boston zipcode:
Tooltip for a non-Boston zipcode:
This removes the [delayUpdate tooltip option](https://github.com/wwayne/react-tooltip#options), intended to prevent other tooltips popping underneath, as it was instead causing the tooltip to jitter to a new location after the delay window, despite the `effect='solid'` setting.
* Hover over "public safety" chart
* Tooltip should display expected text
* Tooltip source and link should be different for zip codes with names starting with "Boston"
* Tooltip links should open in a new window as expected
Closes #220.

Feature/kak/tooltip safety#220

---

taui/configurations/default/messages.yml
taui/src/components/neighborhood-list-info.js
taui/src/constants.js
taui/src/sass/06_components/_neighborhood-facts.scss

Show a link in the school chart's place for Boston and Cambridge (school choice) zip codes, and display a tooltip for the chart.
Tooltip:
Boston school choice:
Cambridge school choice:
The school choice messages are abbreviated from what was requested, as the text would overflow the table.
* Zipcodes with a school ranking chart should display the tooltip as expected
* The link should work and open in a new tab
* Zipcodes for Boston or Cambridge should display a school choice link instead
Closes #219.

Feature/kak/tooltip schools#219

---

taui/src/components/dock.js
taui/src/components/main-page.js

Pass the total count of neighborhoods to the `Dock` component, instead of all neighborhoods.
* Total record counter should still work
Connects #233.

Pass count instead of all neighborhoods

---

taui/configurations/default/messages.yml
taui/src/utils/validate-voucher-number.js

Make voucher ID validation more lax, and relabel as client ID.
Closes #232.
Make the validation rules for voucher IDs more lax, and relabel them as client IDs.
* Search for client IDs
* 6-8 alphanumeric characters should validate
Closes #232.

Change voucher validation and label

---

taui/src/components/meter.js
taui/src/components/neighborhood-list-info.js
taui/src/components/rental-units-meter.js
taui/src/constants.js

Dialed down the hide delay and changed to one tooltip per card instead of per meter. 
This appears to have largely solved the problem.
~However it introduces a new bug. In search view, when mousing into the tooltip itself, the last card in the list gets selected, as if you've hovered on that card. I don't see any simple way of stopping the propagation of that hover event. Fortunately, clicking the link in the tooltip does not trigger a click on the last card. I think this is a net win, given how bad the multiple tooltips problem was. I'll open a new issue for this new bug.~
I initially tried manually hiding all tooltips via `ReactTooltip.hide()` `onMouseEnter` but it didn't work.
Cosmetic change: Tooltips now render to the right, over the map, so as not to occlude other meters.
* Hover …

Fix multiple tooltips bug

---

taui/src/constants.js
taui/src/selectors/neighborhoods-sorted-with-routes.js

Boost the first "downtown" (Boston) zip code into 3rd place, if none are in the top six.
Top results, before:
Top result for Boston is in 13th place:
After, Beacon Hill is boosted to 3rd place:
And another neighborhood is in 13th place:
* Set origin to a location far from downtown
* The first result for a Boston-area zip code should be in third place
* That result should not appear in its previous position (should only be listed once)
Closes #238.

Boost downtown results

---

taui/src/components/neighborhood-details.js
taui/src/sass/06_components/_neighborhood-details.scss
taui/src/utils/google-maps-link.js

Show "Directions" link for transit, too. 
Remove "Google Maps" link from "Learn about…"
* Go to a detail page.
* Click "Directions".
* Confirm Google Maps opens with directions between active neighborhood and selected frequent destination, via current travel mode.
* Repeat for both transit and driving.

Show directions link for transit, too.

---

taui/configurations/default/messages.yml
taui/src/components/neighborhood-details.js
taui/src/sass/06_components/_neighborhood-details.scss

Add a static link to http://bha.cvrapps.com/ to the neighborhood detail page.
* Open a detail page.
* Confirm new link is present and opens http://bha.cvrapps.com/ in a new tab.

Add Rent Estimator link to detail view

---

taui/configurations/default/messages.yml
taui/src/components/dock.js
taui/src/sass/06_components/_map-sidebar.scss
taui/src/sass/06_components/_neighborhood-details.scss

Add feedback link to sidebar footer.
Also made some adjustments to links in the detail page to handle line wrapping.
* On both search and detail pages …
* Confirm feedback link looks reasonable and doesn't collide with other elements at different viewport heights.
* Confirm link opens https://www.mysurveygizmo.com/s3/5088311/ECHOLocator-Feedback-tool in a new tab.
Resolves #182

Add feedback link

---

taui/src/components/meter.js
taui/src/components/rental-units-meter.js
taui/src/utils/scaling.js

Each chart uses its own breaks for the three different colors.
Safety medium break is 21-40%, inclusive (the second quintile):
Schools medium break is 46-65%, inclusive:
* Chart colors should be as expected
Closes #243.

Vary color breaks by chart

---

taui/src/components/edit-profile.js
taui/src/components/select-account.js

Tell browsers to not autofill input form fields to search for a profile or to fill out a profile.
* Go to account search page
* Click into voucher number input field to give it focus
* No previously entered voucher numbers should be suggested by the browser
Closes #271.

Disable input field autocomplete

---

deployment/amplify/staging/amplify/#current-cloud-backend/amplify-meta.json
deployment/amplify/staging/amplify/backend/amplify-meta.json
deployment/amplify/staging/amplify/backend/function/echolocatorStagingProfiles/echolocatorStagingProfiles-cloudformation-template.json
deployment/amplify/staging/amplify/backend/function/echolocatorStagingProfiles/src/app.js

Fix "multiple profiles exist" error being returned for inexact matches.
This has already been pushed to the staging stack.
The `app.js` file is the only one here in need of review; the other changes were autogenerated by pushing the Amplify stack.
* Log in as a counselor
* Create a profile for a six-character voucher number
* Send a client user invite to the six-character voucher profile
* Create a seven- or eight-character voucher number that contains the six-character voucher above
* Log in as client user
* Site should load and go to counselor-created profile matching the voucher for the client
Fixes #278.

Check for exact voucher match at /profiles

---

taui/configurations/default/messages.yml
taui/src/components/edit-profile.js

Adds explanatory text under the transit options on the profile page.
Car:
No commuter rail:
With commuter rail:
The example in #303 shows bolded text for the transit option names, but React doesn't like embedded HTML. (It works with the tooltip messages because they are fed through the tooltip library, which accepts HTML.) If wrapping in `<strong>` tags is important, we could hard-code the strings instead of putting them in `messages.yml`, but this would get in the way of translating the app in future.
* Go to 'edit profile'
* Toggle the transit options and check the explanatory text
* Explanatory text should not show when 'car' is selected
* Text should only be for subway and bus when commuter rail box is unchecked
* Longer text should display when commuter rail box is checked
Closes …

Add explanatory text for transit options on profile page

---

taui/configurations/default/messages.yml
taui/src/components/edit-profile.js
taui/src/components/neighborhood-details.js
taui/src/sass/06_components/_account-profile.scss

1. Add "More search tools" link to [BHA apartment search](https://www.bostonhousing.org/en/Apartment-Listing.aspx?btype=8,7,6,5,4,3,2,1). Reordered the links to maximize the likelihood they'll fit on two lines.
2. Styled the new transit description added in #305 to use a small font-size for hierarchy and max-width to maintain container width.
Resolves #302

Add BHA search tools link. Style profile page transit description.

---

taui/src/constants.js
taui/src/selectors/neighborhoods-sorted-with-routes.js

Ignore school rankings for Boston zip codes.
When boosting Boston zip codes into the top results, boost into the top six (first two pages) rather than the top three (first results page).
Top three results for VERIFY2 on staging (before change):
Top three results for VERIFY2 staging/dev profile on this branch:
* When schools are at least "somewhat important," Boston zipcodes should appear more frequently near the top of the list
* Boosted Boston zipcode results should go on the second page
Closes #272

Feature/kak/boston sort modifications#272

---

taui/src/selectors/neighborhoods-sorted-with-routes.js

Remove special handling to ignore education rankings for Boston neighborhoods.
Closes #317.
I've confirmed the existing Boston neighborhood boosting logic already works as requested (boosts a Boston neighborhood into the sixth slot if there are none in the top six.)
* Neighborhoods should be ranked as expected

Use education rankings for all neighborhoods

---

taui/configurations/default/messages.yml
taui/src/components/edit-profile.js

Assorted small copy changes to the profile page.
Closes #314.
The requested copy included colons at the end of a couple of field labels, which I've omitted here, for consistency with existing field labels.
* (re-)start server (note `messages.yml` changes are not picked up by live reload)
* Text changes should display as requested
* Destination address list section should be above travel mode section

Copy changes to profile page

---

taui/configurations/default/messages.yml
taui/src/components/neighborhood-details.js

Link to "Metro Housing" instead.
Closes #323.
* Go to details for a neighborhood
* Link should be labelled "Metro Housing"
* Link should open Metro Housing site in new tab

Change Mass Housing link
